---
title: "EDA"
author: "Ying"
date: "2020/11/9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Lecture notes of Exploratory Data Analysis (EDA)

```{r}
library(plyr)

auto_data <- read.table("auto.txt", header=FALSE, sep="\t")
#auto_data

auto_data <- rename(auto_data, c(
  "V1"="MPG",
  "V2"="Cylinders",
  "V3"="Displacement",
  "V4"="Horsepower",
  "V5"="Weight",
  "V6"="Acceleration",
  "V7"="ModelYear",
  "V8"="Origin",
  "V9"="CarName"
  ))
```

```{r}
x <- auto_data[[3]]
mean(x)
var(x)
n <- length(x)
n
```

jitter plot, lossless
```{r}
library(ggplot2)
ggplot(auto_data, aes(x=Displacement,y=rep(1,n)))+ geom_jitter() + ylim(0,2) + ylab("Random Y")
```

```{r}
ggplot(auto_data, aes(x=Displacement)) + geom_histogram()
```


```{r}
ggplot(auto_data, aes(x=Displacement)) + geom_density()
```




```{r}
colMeans(auto_data[,1:7], na.rm = TRUE)
cov(auto_data[,1:7], use = "na.or.complete")
cor(auto_data[,1:7], use = "na.or.complete")
```


A 2d histogram generalised the univariate in the natural wayas the count of data points falling inside a given two-dimensional area.
```{r}
ggplot(auto_data, aes(x=Displacement,y=Weight)) + geom_bin2d()
```



the area need not be a rectangle!
```{r}
ggplot(auto_data, aes(x=Displacement,y=Weight)) + geom_hex()
```



```{r}
ggplot(auto_data, aes(x=Displacement,y=Weight)) + geom_density_2d()
```

```{r}
ggplot(auto_data, aes(x=Displacement,y=Weight)) + geom_point()
```

```{r}
ggplot(auto_data, aes(x=Displacement,y=Weight)) + geom_point(aes(color=Acceleration),size=auto_data$Horsepower/50)+ ggtitle("Point Size is Proportional to Horsepower")
```






